### ISSUE TITLE
Case #400 has wrong date

### ISSUE THREAD

**Issue by tillnagel** [iceweasel1/COVID-19-Germany#6]
Case #400 has a transposition error in the date. CSV says 05/03/2020, while correct seems to be 03/05/2020 (source says 03/04/2020).

`400,05/03/2020,Schleswig-Holstein,Dithmarschen,54.08,9.08,"https://www.dithmarschen.de/Quicknavigation/Startseite/Bestätigter-Corona-Fall-bei-einer-Mitarbeiterin-der-Westküstenkliniken-in-Heide.php?object=tx,2046.1&ModID=7&FID=2046.8072.1&NavID=2046.1&NavID=2046.15"`

**Comment by iceweasel1** [comment]
Thanks @tillnagel. Yeah, this number twister is mine.  I didn't mean to. There will be a new update in an hour and a half with the current 836 confirmed cases.  There I correct the error with the date.

**Comment by tillnagel** [comment]
Fixed with 02e90c9

**Comment by iceweasel1** [comment]
Thanks again for the advice. Sorry it took an extra day. Sorry.

**Comment by tillnagel** [comment]
Thanks for all your hard work!
